title: 로그로그
description: 세상에 나의 로그를 남기자
show_downloads: false

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://tk2blog90.github.io" # change this to the base hostname & protocol for your site
paginate_path: '/page:num/'
paginate: 3

google_analytics:

date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: tk2rush90
image: /thumbnail.png

plugins:
  - jekyll-target-blank
  - jekyll-paginate

target-blank:
    rel: nofollow

